### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Immortalin** [leifg/excellent#5]
```
 == Compilation error on file lib/excellent/parser.ex ==
** (RuntimeError) error parsing file /usr/lib/erlang/lib/xmerl-1.3.8/include/xmerl.hrl, got: {:error, :enoent}
    (elixir) lib/record/extractor.ex:80: Record.Extractor.read_file/1
    (elixir) lib/record/extractor.ex:50: Record.Extractor.extract_record/2
    lib/excellent/parser.ex:4: (module)
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

could not compile dependency :excellent, "mix compile" failed. You can recompile this dependency with "mix deps.compile 
excellent", update it with "mix deps.update excellent" or clean it with "mix deps.clean excellent"            
```

**Comment by Immortalin** [comment]
Solved  by installing erlang separately using apt instead of using the default one bundled with elixir.
